### ISSUE TITLE
Error migrate database

### ISSUE THREAD

**Issue by kocik799** [nautobot/nautobot-plugin-device-onboarding#110]
### Environment
* Python version:  3.8.16
* Nautobot version:  2.0.0
* nautobot-device-onboarding version:  latest
* OracleLinux 8 latest

### Steps to Reproduce
1. new install nautobot
2. install nautobot-device-onboarding
3. nautobot-server post_upgrade
 

### Observed Behavior
04:30:15.901 ERROR   nautobot.core.apps :
  Error in link construction for Notes: Reverse for 'note_list' not found. 'note_list' is not a valid view function or pattern name.
Performing database migrations...
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/management/commands/post_upgrade.py", line 100, in handle
    call_command(
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration dcim.0028_alter_device_and_rack_role_add_new_role is applied before its dependency nautobot_device_onboarding.0001_initial on database 'default'.

**Comment by scetron** [comment]
Thank you for the report, what method did you use to install nautobot?

**Comment by glennmatthews** [comment]
Sounds like the app *might* need to provide a squashed migration for fresh installation atop an existing 2.0 install (as opposed to upgrading to 2.0 when the app is already installed, or installing both 2.0 and the app at the same time). Just a guess.

**Comment by scetron** [comment]
I believe that is correct, I will issue a fix as soon as possible.

**Comment by kocik799** [comment]
> Thank you for the report, what method did you use to install nautobot?

hi, used the official instructions https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/installation/

**Comment by JonathanNathanson** [comment]
I have had a similar issue with nautobot 2.0.1 / python 3.8.10 :

nautobot@nautobot:~$ nautobot-server --version
2.0.1

`nautobot@nautobot:~$ nautobot-server post_upgrade
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/nautobot/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 848, in ready
    super().ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 71, in ready
    registry["new_ui_ready_routes"].update(get_all_new_ui_ready_routes())
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/utils/navigation.py", line 47, in get_all_new_ui_ready_routes
    url_patterns = resolver.url_patterns
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/urls.py", line 7, in <module>
    from nautobot.extras.plugins.urls import (
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/urls.py", line 32, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 46, in import_object
    spec.loader.exec_module(module)
  File "/opt/nautobot/lib/python3.8/site-packages/welcome_wizard/urls.py", line 6, in <module>
    from . import views
  File "/opt/nautobot/lib/python3.8/site-packages/welcome_wizard/views.py", line 13, in <module>
    from nautobot.dcim.models import Site, DeviceType, Manufacturer
ImportError: cannot import name 'Site' from 'nautobot.dcim.models' (/opt/nautobot/lib/python3.8/site-packages/nautobot/dcim/models/__init__.py)`

Disabling nautobot_device_onboarding in the configuration file as described in the uninstall docs here doesn't resolve:

https://docs.nautobot.com/projects/device-onboarding/en/latest/admin/install/

**Comment by glennmatthews** [comment]
@JonathanNathanson The `nautobot_welcome_wizard` plugin hasn't yet been updated for 2.0 compatibility.

**Comment by JonathanNathanson** [comment]
Makes sense, thanks for the update. I should have been more thorough while checking the compatibility matrix before I went ahead and installed it (both plugins actually). 

I guess this means that my nautobot install is broken without an easy fix, so best to start again?

**Comment by scetron** [comment]
@kocik799 @JonathanNathanson the latest release (v2.0.2) should fix issues with new installs + upgrades. Let us know if there are any issues!

**Comment by kocik799** [comment]
@scetron  Hello, thanks, everything works.

**Comment by scetron** [comment]
Closed by #113
