### ISSUE TITLE
Prefix get or create is broken caused by type attribute typo

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-plugin-device-onboarding#122]
https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/152b70289e9e3a54c16d5236d7f471749c368e5a/nautobot_device_onboarding/nautobot_keeper.py#L466C27-L466C27

Needs to be `type="network"` where network is lowercase.  Otherwise it doesn't find a network.

```python
>>> a = Prefix.objects.get(prefix=f"{prefix.network}",namespace=Namespace.objects.get(name="Global"), type="Network")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/ipam/querysets.py", line 256, in get
    return super().get(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
nautobot.ipam.models.Prefix.DoesNotExist: Prefix matching query does not exist.
>>>
>>> a = Prefix.objects.get(prefix=f"{prefix.network}",namespace=Namespace.objects.get(name="Global")))
>>> a.type
'network'
>>>
>>> a = Prefix.objects.get(prefix=f"{prefix.network}",namespace=Namespace.objects.get(name="Global"), type="network")
>>> a
<Prefix: 10.171.246.0/24>
```

**Comment by jeffkala** [comment]
as an FYI, the actual error when executing the onboarding in this scenario is.


failed | fail-general | duplicate key value violates unique constraint "ipam_prefix_namespace_id_network_prefix_length_b2dd8b57_uniq" DETAIL: Key (namespace_id, network, prefix_length)=(a5670161-de39-401e-8e93-157ce7a1930d, \<redacted>, 24) already exists.
