### ISSUE TITLE
nautobot-server migrate fails when installing plugin

### ISSUE THREAD

**Issue by heimberg** [nautobot/nautobot-plugin-device-onboarding#51]
### Environment
* Python version:  3.8.10
* Nautobot version:  3.8.10
* nautobot-device-onboarding version:  1.1.2

### Steps to Reproduce
1. Fresh Installation of nautobot
2. Plugin installation as described in the documentation
3. `nautobot-server migrate`

### Expected Behavior
Succesful migration and thus installation of the plugin

### Observed Behavior
Migration fails with exception `PluginNotFound`

```
nautobot@nautobot:~$ nautobot-server migrate
Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 64, in load_plugin
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nautobot-device-onboarding'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 116, in settings_callback
    initializer(
  File "/opt/nautobot/.local/lib/python3.8/site-packages/nautobot/core/cli.py", line 176, in _configure_settings
    load_plugins(settings)
  File "/opt/nautobot/.local/lib/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 54, in load_plugins
    load_plugin(plugin_name, settings)
  File "/opt/nautobot/.local/lib/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 67, in load_plugin
    raise PluginNotFound(
nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot-device-onboarding: Module not found. Check that the plugin module has been installed within the correct Python environment.
```

**Comment by glennmatthews** [comment]
Looks like maybe you might have set `PLUGINS = ["nautobot-device-onboarding"]` instead of `PLUGINS = ["nautobot_device_onboarding"]`?

**Comment by scetron** [comment]
@heimberg If you are still having issues with the plugin please feel free to reopen this issue or open a new one. Thank you.
