### ISSUE TITLE
cloudvision -> nautobot indexerror: list index out of range

### ISSUE THREAD

**Issue by ddrew83** [nautobot/nautobot-plugin-device-onboarding#69]
### Environment
* Python version:  3.10
* Nautobot version:  1.5.7
* nautobot_ssot_aristacv 1.4.0
* ssot : 1.2.0

 **Steps to Reproduce**
1.Plugins, dashboard, single source of truth
2.Cloudvision --> Nautobot
3. Debug and Dry run, Run job now

Pull data from CVP into Nautobot, or at least show me what its going to pull in.

After several logs entries showing interface details for each device-
Loading data from Nautobot
Then a failure - An exception occurred: IndexError: list index out of range

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 146, in sync_data
    self.load_target_adapter()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/jobs.py", line 123, in load_target_adapter
    self.target_adapter.load()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/nautobot.py", line 41, in load
    version=nautobot.get_device_version(dev),
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/utils/nautobot.py", line 107, in get_device_version
    version = relations["destination"][software_relation][0].source.version
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

**Comment by scetron** [comment]
Hello! I believe you are looking for the CloudVision importer:  https://github.com/nautobot/nautobot-arista-cloudvision-importer

Or perhaps the CloudVision SSOT plugin:

https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision

**Comment by ddrew83** [comment]
Hi, yes its the https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision which is failing

**Comment by scetron** [comment]
Please open an issue under that Repo. Feel free to open another issue here or reopen this issue if you need anything!  Thank you.
